feat(community-tabs): add support for wrapping labels
telus/tds-community pull request #437
Opened 2021-01-27 17:57 UTC by mburtch

## Description

### Feature
Adds support for optionally wrapping tab labels to multiple lines, for use in marketing contexts, following the [provided designs](https://telus.invisionapp.com/d/main#/console/18077659/426618923/inspect). The Boolean `wrapLabels` prop will limit the max-width of labels to 144px, wrapping as necessary.

### Fixes
While building this feature, the following issues were identified and fixed:
- **IE11 support**: the scrolling tabs feature would crash in IE11 due to lack of [NodeList.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) support
- **props/attrs warnings**: deconstruct `open`/`onOpen` props to remove from `rest`; fix issues with `tabIndex` attributes (case-sensitivity, undefined, null)
- **layout improvements**: better align the label spacing, improve focus rings, and address shifting on select/focus, to more closely follow the designs:

![image](https://user-images.githubusercontent.com/93336/106032736-dafc5000-609e-11eb-96cf-ddaa71b65d07.png)

## Checklist before submitting pull request

- Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
- [X] New code is unit tested
- [X] make sure visual and accessibility tests pass
- [X] make sure code builds

2021-01-29 18:50 UTC, Andrew-K-Lam commented on packages/Tabs/styles.jsx
> +  border-top: solid 4px ${isSelected ? '#71757b' : '#d8d8d8'};
Use TDS Core colours when possible

2021-01-29 18:50 UTC, Andrew-K-Lam submitted a review, later dismissed
Use TDS Core colours when possible

2021-02-02 19:16 UTC, jraff approved these changes
LGTM

2021-02-02 19:23 UTC, jraff requested changes
Can you please add documentation and a code sample for the new `warpLabels` property

2021-02-03 16:18 UTC, jraff approved these changes

2021-02-03 19:42 UTC, merged