feat(community-story-card): implement initial code for story card
telus/tds-community pull request #507
Opened 2021-06-16 20:35 UTC by julia-dufresne

2021-06-18 17:15 UTC, Andrew-K-Lam requested changes

2021-06-18 17:15 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +StoryCard.propTypes = {
None of your props are required, so if I create the component with no props, it throws an error: TypeError: Cannot read property 'toLowerCase' of undefined

2021-06-18 19:20 UTC, Andrew-K-Lam requested changes

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +    const normalizedType = type.toLowerCase()
You'll need a check here if no storyType is undefined, toLowerCase crashes the component if no prop is passed

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +    <StyledLink href={slug}>
Need to add a title for the link so user knows where the link is going

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/style.js
> +
Use REM instead of px when possible.  Some places may not be but font-size, border radius, it makes sense to use REM

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +      return <News size="20" />
Size prop should be an integer and not a string.  These lines are causing warnings in console.

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +  slug: PropTypes.string,
Better name for this would be href

2021-06-18 19:20 UTC, Andrew-K-Lam commented on packages/StoryCard/StoryCard.jsx
> +  imgUrl: PropTypes.string,
Do you expect Videos to be an option?  If so, take a look at what PreviewCard does.
If not, imgUrl prop could be changed to be more consistent with another component (<PreviewCard />)
https://github.com/telus/tds-community/blob/master/packages/PreviewCard/PreviewCard.jsx#L156

2021-06-21 18:32 UTC, Andrew-K-Lam approved these changes

2021-06-21 18:33 UTC, Andrew-K-Lam commented
LGTM

2021-06-22 14:48 UTC, jraff requested changes
@julia-dufresne Please change the commit message to reflect the changes

`feat(community-story-card): add story card`

2021-06-22 15:00 UTC, jraff approved these changes

2021-06-22 15:12 UTC, merged