Feat/HNT-241 - Next gen modal
telus/tds-community pull request #521
Opened 2021-07-09 18:19 UTC by archit-mahto

## Related issues

See 

## Description

- Feature 1
- Feature 2
- Patch 1
- Patch 2

## Checklist before submitting pull request

- Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
- [x] New code is unit tested
- [ ] make sure visual and accessibility tests pass
- [ ] make sure code builds

2021-07-13 14:21 UTC, archit-mahto commented on packages/Modal/Footer/Footer.jsx
> +/* eslint-disable no-unused-vars */
I can do that

2021-07-13 14:22 UTC, MarielleRobertsTelusDigital commented on packages/Modal/Modal.jsx
>   */
delete comment

2021-07-13 14:23 UTC, MarielleRobertsTelusDigital commented on packages/Modal/styles.jsx
> +  // paddingTop: '1rem',
delete comment.

2021-07-13 14:23 UTC, MarielleRobertsTelusDigital commented on packages/Modal/styles.jsx
> +  // marginTop: '1rem',
delete unused code.

2021-07-13 14:24 UTC, MarielleRobertsTelusDigital requested changes
Great job! Just delete unused/commented code!

2021-07-13 14:31 UTC, archit-mahto commented on packages/Modal/Modal.jsx
>   */
I don't see the comment in my file

2021-07-13 17:13 UTC, KetanAgarwal approved these changes
Looks fine to me.

2021-07-14 12:54 UTC, MarielleRobertsTelusDigital approved these changes

2021-07-19 11:43 UTC, KetanAgarwal reviewed
Why are we changing the whole modal as the impact will be high with such change ? Instead of changing the current community modal I think we should create a new package for the new modal. And for the current community modal just give them the option to change or update the variant of buttons from a prop.

2021-07-21 15:08 UTC, merged